import Head from "next/head";
import { useRouter } from "next/router";
import { useEffect, useState } from "react";
import Main from "../components/Main";
import SearchBox from "../components/SearchBox";
import Title from "../components/Title";
import state from "../store";

export default function Home({ json }) {

 
  


  
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Title />

     

      <SearchBox json={json} />

      <Main />
    </>
  );
}

// components

// get server side props
export async function getServerSideProps() {


 


  const res = await fetch(
    "https://api.coingecko.com/api/v3/coins/markets?vs_currency=usd&order=market_cap_desc&per_page=10&page=1&sparkline=false"
  );
  const json = await res.json();

 // set timeout to simulate a slow server
 

  return {
    props: {
      json,
    },
  };
}
