import Head from "next/head";
import Main from "../components/Main";

export default function Home({ json ,json2}) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/*       <pre>{JSON.stringify(json2, null, 2)}</pre>
       */}
      {json.map(
        (
          { open, close, time_open, time_close, high, low, volume, market_cap },
          index
        ) => {
          return (
            <Main
              key={index}
              open={open}
              close={close}
              time_open={time_open}
              time_close={time_close}
              high={high}
              low={low}
              volume={volume}
              market_cap={market_cap}
            />
          );
        }
      )}

      {/* <pre>{JSON.stringify(json, null, 2)}</pre> */}
      {/*     <Main  /> */}
    </>
  );
}

// components

// get server side props
export async function getServerSideProps() {
  const API = process.env.api;
  // make async call to external API
  //https://api.coinpaprika.com/#tag/Coins/paths/~1coins~1{coin_id}~1ohlcv~1historical/get

  const res = await fetch(
    "https://api.coinpaprika.com/v1/coins/btc-bitcoin/ohlcv/today"
  );

  const json = await res.json();

// make a fetch call to an api endpoint
 const res2 = await fetch(
   `https://api.coinpaprika.com/v1/exchanges/`
 );
 const json2 = await res2.json();



  return {
    props: {
      json,
      json2
    },
  };
}
